site_name: My Docs


pages:
- Home: 'index.md'
- Φυσική:
    - 'Θεωρία Γυμν': 'pdf/theory-gymn.md'
    
- Χημεία:
    - 'License': 'index.md'
    - 'Release Notes': 'index.md'
- Παλιές Αναρτήσεις:
    - 'License': 'index.md'
    - 'Release Notes': 'index.md'
