site_name: My Docs


pages:
- Home: 'index.md'
- User Guide:
    - 'Writing your docs': 'index.md'
    - 'Styling your docs': 'index.md'
- About:
    - 'License': 'index.md'
    - 'Release Notes': 'index.md'
