site_name: My Docs


pages:
- Home: 'index.md'
- Φυσική:
    - 'Writing your docs': 'index.md'
    - 'Styling your docs': 'index.md'
- Χημεία:
    - 'License': 'index.md'
    - 'Release Notes': 'index.md'
